#!/bin/bash

echo "=========================================="
echo "  RISC-V CPU Development Environment"
echo "=========================================="
echo ""
echo "Installed tools:"
echo "  - Neovim + LazyVim          : Editor"
echo "  - Icarus Verilog (iverilog) : Verilog compilation/simulation"
echo "  - Verilator                 : High-speed Verilog simulation"
echo "  - GTKWave                   : Waveform viewer"
echo "  - RISC-V GCC Toolchain      : Cross compiler"
echo "  - cocotb                    : Python testbench"
echo ""
echo "Directory structure:"
echo "  /workspace/rtl   - Verilog RTL source code"
echo "  /workspace/tb    - Testbench files"
echo "  /workspace/sim   - Simulation output (waveforms, etc.)"
echo "  /workspace/sw    - Software/firmware programs"
echo "  /workspace/docs  - Documentation"
echo ""
echo "Quick commands:"
echo "  nvim .                                  # Open editor"
echo "  make sim                                # Run simulation"
echo "  make wave                               # View waveforms"
echo ""
echo "Neovim hotkeys (Leader = Space):"
echo "  <Space>vs  - Run Verilog simulation"
echo "  <Space>vw  - Open GTKWave"
echo "  <Space>vc  - Clean build files"
echo "  <Space>rc  - Compile RISC-V software"
echo "  <Space>fr  - Search RTL files"
echo "  <Space>ft  - Search Testbench files"
echo "  <Space>e   - File tree"
echo "  <Space>ff  - Search files"
echo "  <Space>fg  - Global search"
echo ""
echo "=========================================="

exec "$@"
